Force the python version to 3.8.2
Without the fix, we get the error

```
Traceback (most recent call last):

  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3552, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)

  File "/tmp/ipykernel_59/3601587137.py", line 2, in <module>
    import emeval.input.spec_details as eisd

  File "<fstring>", line 1
    (post_body=)
              ^
SyntaxError: invalid syntax
```

This works on my local environment with python 3.8.2

```
Set up the dependencies

import emeval.input.spec_details as eisd
import emeval.input.phone_view as eipv
import emeval.input.eval_view as eiev

import sys
sys.version

'3.8.2 (default, Mar 25 2020, 11:22:43) \n[Clang 4.0.1 (tags/RELEASE_401/final)]'
```

So forcing the environment to 3.8.2 so we don't have to go around and fix all the f-strings